name: TechSolution
favicon: null
layout_spectrum: 0.24253
typography_spectrum: 0.497279301751405
title: 'We Come To You!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c3e50'
    - '#c5d82d'
    - '#6f7c88'
    - '#ccd0da'
  brandStrength: 0
  lightness: 0.4965714910067618
  saturation: 0.5
  rhythmicContrast: 0.8366298431064934
purpose: []
