name: TechSolution
favicon: null
layout_spectrum: 0.5194707605987787
typography_spectrum: 0.497279301751405
title: 'We Come To You!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c3e50'
    - '#c5d82d'
    - '#82953c'
    - '#000000'
    - '#ffff00'
  brandStrength: 0.7353707691654563
  lightness: 0.4965714910067618
  saturation: 0.9696691983845085
  rhythmicContrast: 0.8366298431064934
purpose: []
