name: TechSolution
favicon: null
layout_spectrum: 0.5194707605987787
typography_spectrum: 0.497279301751405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7353707691654563
  lightness: 0.4965714910067618
  saturation: 0.9696691983845085
  rhythmicContrast: 0.8366298431064934
purpose: []
