name: TechSolution
favicon: null
layout_spectrum: 0.24253
typography_spectrum: 0.497279301751405
title: Computer Repair
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76728311-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c3e50'
    - '#c5d82d'
    - '#82953c'
    - '#000000'
    - '#ffff00'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.8366298431064934
purpose: []
