name: TechSolution
favicon: null
layout_spectrum: 0.24253
typography_spectrum: 0.497279301751405
title: 'Tech Solution LLC "We Come to You!"'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0352ae'
    - '#0a8ef3'
    - '#ffffff'
    - '#62a32d'
    - '#f89a43'
  brandStrength: 0
  lightness: 0.4965714910067618
  saturation: 0.5
  rhythmicContrast: 0.8366298431064934
purpose: []
