analytics: {}
color:
  brandColors:
    - '#2c3e50'
    - '#c5d82d'
    - '#82953c'
    - '#000000'
    - '#ffff00'
  brandStrength: 0
  lightness: 0.625
  rhythmicContrast: 0.8366298431064934
  saturation: 0.5
cta: {}
layout_spectrum: 0.24253
name: TechSolution
opengraph: {}
purpose: []
typography_spectrum: 0.497279301751405
